sudo: required
language: bash
services:
  - docker
stages:
  - version
  - build_test
  - build_and_push
  - nectar
before_script:
  - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
after_script:
  - docker logout
jobs:
  include:
    - stage: version
      if: branch = master AND (type IN (push))
      script:
        - git checkout master;
        - docker pull govtechsg/cicd-images:vtscripts-latest;
        - docker run -v "$(pwd):/app" -w "/app" govtechsg/cicd-images:vtscripts-latest iterate patch -q -i;
        - git push -q https://${GH_USERNAME}:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git --tags;
    - stage: build_test
      if: branch = master AND (type IN (pull_request))
      language: node_js
      node_js:
        - "10.14.1"
      script:
        - npm install -g typescript
        - tsc --project ./tsconfig-prod.json
        - docker build .;
    - stage: build_and_push
      language: node_js
      node_js:
        - "10.14.1"
      if: branch = master AND (type IN (push))
      script:
        - npm install -g typescript
        - echo "Current Commit= $TRAVIS_COMMIT";
        - CURRENT_TAG=$(git describe --tags --exact-match "$TRAVIS_COMMIT");
        - echo "Current Tag= $CURRENT_TAG";
        - tsc --project ./tsconfig-prod.json
        - docker build -t "${DH_REPO}":"${CURRENT_TAG}" .;
        - docker tag "${DH_REPO}":"${CURRENT_TAG}" "${DH_REPO}":latest;
        - docker push "${DH_REPO}":"${CURRENT_TAG}";
        - docker push "${DH_REPO}":latest;
    - stage: nectar
      if: branch = master AND (type IN (push))
      script:
        - IMAGE_NAME=$(echo ${DH_REPO} | sed 's:.*/::');
        - CURRENT_TAG=$(git describe --tags --exact-match "$TRAVIS_COMMIT");
        - git checkout ${TRAVIS_BRANCH};
        - 'sed -i "1 s/^.*/FROM govtechsg\/${IMAGE_NAME}:${CURRENT_TAG}/" ./Nectar.Dockerfile'
        - git add Nectar.Dockerfile;
        - 'git commit --allow-empty -m "RELEASE: ${CURRENT_TAG} Image Name: ${IMAGE_NAME}:${CURRENT_TAG} [ci skip]"'
        - git push -q https://${GH_USERNAME}:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git;
