version: "3"
services:
  proxy:
    container_name: apex_proxy
    build: .
    environment:
      AUTH_MODE: APPEND
      LOCAL_PORT: 1337
      TARGET_HOST: example.com
      TARGET_PORT: 80
      APP_ID: test
      L1_INTERNAL: 'true'
      L1_SECRET: secret
      L2_INTERNAL: 'false'
      L2_KEY_FILE: 
      L2_KEY_STRING: 
    expose:
      - "1337"
    ports:
      - "1337:1337"
    working_dir: /app