version: "3"
services:
  proxy:
    container_name: apex_proxy
    # build: .
    image: apex-proxy-node:prod
    environment:
      DEBUG: "true"
      AUTH_MODE: APPEND
      LOCAL_PORT: 1337
      SECURE: "false"
      # Forward proxy settings
      #HTTP_PROXY: https://abc:abc@266.266.266.266:333
      #USE_PROXY_AGENT: "true"
      #TO_PROXY: "true"
      # First Gateway
      GATEWAY_IS_SINGLE: "true"
      GATEWAY_1_HOST: mcf.api.gov.sg
      GATEWAY_1_SIGNING_HOST: mcf.e.api.gov.sg
      GATEWAY_1_PORT: 443
      GATEWAY_1_TYPE: EXTERNAL
      GATEWAY_1_URL_PREFIX: app-internet
      GATEWAY_1_APP_ID: app-id
      #GATEWAY_1_SECRET: secretpassword
      #GATEWAY_1_KEY_STRING:
      #GATEWAY_1_KEY_FILE: /private.pem
      # Second Gateway
      GATEWAY_2_HOST: <yourproject>.api.xxx.sg
      GATEWAY_2_SIGNING_HOST: <yourproject>.i.api.xxx.sg
      GATEWAY_2_PORT: 443
      GATEWAY_2_TYPE: INTERNAL
      GATEWAY_2_URL_PREFIX: app-intranet
      GATEWAY_2_APP_ID: app-id2
      #GATEWAY_2_SECRET: secretpassword
      #GATEWAY_2_KEY_STRING:
      #GATEWAY_2_KEY_FILE: /private.pem
    expose:
      - "1337"
    ports:
      - "1337:1337"
    working_dir: /app
